server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # כאן הקסם: כל בקשה שמתחילה ב-/api תעבור ל-Backend
    location /api/ {
        proxy_pass http://backend-service:8080/; 
        proxy_http_version 1.1;
    }
}