server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # זהו השינוי הקריטי:
    location /api/ {
        # 1. שם השרת הוא 'backend' (כפי שהגדרנו ב-docker-compose)
        # 2. הפורט הוא 3000 (כי זה הפורט שה-Node.js מאזין לו בתוך ה-Container)
        proxy_pass http://backend:3000/; 
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}